print ("helo from snowball")
print ("a print from pycharm")
print ("hold on")
print ("hey bro")
print ("The core difference is that git clone is for creating a new, local copy of an entire repository from a remote source, while git push is for uploading local changes from an existing local repository back up to a remote repository")